### ISSUE TITLE
Convert Records to XML

### ISSUE THREAD

**Issue by Maltwind** [scmmmh/polymatheia#4]
It would be awesome, if it possible to get the records as xml

**Comment by scmmmh** [comment]
This can be implemented. The serialisation would be very simple, with keys in the records converted into XML tags and the values as the tag contents.

For example the following record:

```
{
    "key1": "value",
    "key2": "value 2
]
```

would be serialised as

```
<record>
  <key1>value</key1>
  <key2>value</key2>
</record>
```

Would this be acceptable?
