### ISSUE TITLE
Add Readers for fetching data from SRU endpoints

### ISSUE THREAD

**Issue by alueschow** [scmmmh/polymatheia#5]
Can be quite similar to the implementation of Readers for OAI-PMH endpoints.

I started working on a Python SRU library (inspired by [Sickle](https://github.com/mloesch/sickle)) to make the integration into Polymatheia as smooth as possible: [SRUpy](https://github.com/alueschow/srupy).

I already added the appropriate classes to Polymatheia, see my pull request.

**Comment by scmmmh** [comment]
Why the development of a new library (SRUpy), rather than using the existing sruthi?

**Comment by alueschow** [comment]
Basically, there are 2 reasons:
(1) I thought it would be a good idea to keep the structure similar to Sickle for maintenance reasons.
(2) I wasn't aware of sruthi until I published SRUpy to PyPi.

So we can as well rely on sruthi, I don't have a preference here

**Comment by scmmmh** [comment]
I also do not have a preference. The question is more whether you would want to maintain the extra library?
